[project]
name = "pyexample"
version = "0.1.0"
description = "Example Data Science Project with Python (no tools like uv/poetry/conda)"
readme = "README.md"
license = "GPL-3.0-or-later"
requires-python = ">=3.12"
dependencies = [
    "pytest",
    "pandas>=2.0.0",
    "jupyter",
]

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"
